"""Regression tests for repository hygiene -- gitignore entries and a
guard against re-tracking auto-generated user state files.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parent.parent
GITIGNORE = REPO_ROOT / ".gitignore"


def _gitignore_lines() -> list[str]:
    return [ln.strip() for ln in GITIGNORE.read_text().splitlines() if ln.strip()]


class TestGitignore:
    def test_gitignore_exists(self) -> None:
        assert GITIGNORE.exists()

    def test_tui_history_file_is_ignored(self) -> None:
        assert any(
            ".agent/tui_history.jsonl" == ln for ln in _gitignore_lines()
        ), (
            ".agent/tui_history.jsonl is generated by the TUI on startup and "
            "must stay out of git -- otherwise every test or local run "
            "shows up as a dirty working tree."
        )

    def test_loop_runtime_dir_is_ignored(self) -> None:
        assert any(".loop/" == ln for ln in _gitignore_lines())

    def test_venv_serve_is_ignored(self) -> None:
        assert any(".venv-serve/" == ln for ln in _gitignore_lines())


class TestNotTracked:
    """The TUI auto-creates ``.agent/tui_history.jsonl`` when the App
    starts. If a previous loop committed it accidentally, this test fails
    so the next loop notices and runs ``git rm --cached`` on it."""

    def test_tui_history_file_not_tracked(self) -> None:
        try:
            proc = subprocess.run(
                ["git", "ls-files", ".agent/tui_history.jsonl"],
                cwd=REPO_ROOT,
                capture_output=True,
                text=True,
                check=True,
                timeout=10,
            )
        except (FileNotFoundError, subprocess.SubprocessError) as exc:
            pytest.skip(f"git not usable in this environment: {exc}")
        assert proc.stdout.strip() == "", (
            "tracked auto-generated TUI history file: "
            "run `git rm --cached .agent/tui_history.jsonl`"
        )
